name: Linter

on:
    push:
        branches:
            - main
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14, 15, 16]

        steps:
            - uses: actions/checkout@v4
            - name: Typescript Linting
              run: |
                  npm install prettier -g
                  prettier --tab-width 4 --use-tabs true  --check "src/**/*.ts"
