name: npm publish
on: [push]

jobs:
    publish:
        name: release
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "14, 15, 16"
            - name: Install dependencies
              run: npm ci
            - name: Release
              env:
                  run: npm run semantic-release
